***Welcome***

In [5]:
import numpy as np

In [ ]:
myarr=np.array([2,4,6,8,10,12,11,9,7,5,3,1],np.int8)            #create a numpy array from python structures
myarr

array([ 2,  4,  6,  8, 10, 12, 11,  9,  7,  5,  3,  1], dtype=int8)

In [11]:
myarr.dtype           
myarr.shape

(12,)

In [ ]:
myarr1=np.array([[2,4,6,8,10,12],[11,9,7,5,3,1]])            #create a numpy n dimensional array from python structures
myarr1

array([[ 2,  4,  6,  8, 10, 12],
       [11,  9,  7,  5,  3,  1]])

In [10]:
myarr1[1,5]=0
myarr1

array([[ 2,  4,  6,  8, 10, 12],
       [11,  9,  7,  5,  3,  0]])

In [11]:
zeros=np.zeros((3,3))          #creating numpy array with zeros 
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones=np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
a=np.full((12,3),45)
a

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [23]:
a=([1,2,3],[4,5,6],[7,8,9])
ar=np.array(a)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.sum(axis=0)      #sum of element row wise

array([12, 15, 18])

In [ ]:
ar.sum(axis=1)              #sum of all element column wise

array([ 6, 15, 24])

In [ ]:
ar.T                #Transpose array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar.flat                      #print all element through flat
for item in ar.flat :
    print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.ndim          #find number of dimensional array

2

In [ ]:
ar.nbytes              #find how many bytes take by my array

72

In [ ]:
ar.argmax()              #find the index which maximun number in the array

np.int64(8)

In [ ]:
ar.argmax(axis=0)        #find the index which maximun number in the array in the axies

array([2, 2, 2])

In [ ]:
ar.ravel()                #output:array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a=([9,8,7],[6,5,4],[3,2,1])
ar2=np.array(a)
ar2


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
ar+ar2                  #sum both array elements

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])